# DX 602 Week 6 Homework






## Introduction

Practice is a large part of becoming fluent in a programming language.
In this module, you will be assigned regular coding homework to practice Python.
If these problems seem too easy to you, try to answer them faster, and make sure to check the auto-grader feedback to confirm the correctness of your answers.
Like with spoken languages, fluency (speed) is highly correlated with proficiency.
But it is important to answer the problems correctly first, then quickly.


## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [9]:
import math
import sys

import matplotlib.pyplot as plt
import numpy as np

## Problems

### Problem 1

Set `p1` to the sum of the values in `q1`.

In [10]:
# DO NOT CHANGE

q1 = np.array([[[ 0.98000311, -0.35956482,  1.00232898, -1.45209838],
        [-0.67175911, -0.84953269,  0.10704931,  0.41754274],
        [ 0.53522584, -1.55733964, -1.03784553, -0.23711248]],
       [[ 0.16800128, -2.28326782,  0.67403402, -0.06765582],
        [-0.61726066, -0.35678495, -0.87902535, -1.7904995 ],
        [ 1.41477031,  1.24684156, -0.23343696,  0.88934047]]])

In [11]:
# YOUR CHANGES HERE

p1 = ...

In [12]:
p1

Ellipsis

### Problem 2

Write a function `p2` taking an array as input, and returning an array of the same shape with each value squared.

In [13]:
# YOUR CHANGES HERE

def p2(a):
    ...

In [14]:
p2_test_1 = np.arange(10)
p2_test_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
p2(p2_test_1)

In [16]:
p2_test_2 = p2_test_1.reshape(5, 2)
p2_test_2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
p2(p2_test_2)

### Problem 3

Write a function `p3` taking in input $n$, an integer, and creating an array whose contents are $0^2, 1^2, 2^2, \ldots, (n-1)^2$.

Hint: Start from `np.arange`.

In [18]:
# YOUR CHANGES HERE

def p3(n):
    ...

In [19]:
p3(5)

In [20]:
p3(1)

In [21]:
p3(0)

### Problem 4

Write a function `p4` that takes in an array and returns `True` if it uses more than 1,000,000 bytes and `False` otherwise.

In [ ]:
# YOUR CHANGES HERE

def p4(a):
    ...

In [ ]:
p4(np.zeros(0))

In [ ]:
p4(np.zeros(1000))

In [ ]:
p4(np.zeros(100000))

In [ ]:
p4(np.zeros(1000000))

### Problem 5

For charts based on known functions, it is often convenient to generate a variable containing evenly spaced x values to plot.
Set `p5` to be 100 evenly spaced values starting at zero and ending at ten.

In [ ]:
# YOUR CHANGES HERE

p5 = ...

In [ ]:
p5

### Problem 6

Write a function `p6` that takes in two arrays, one with shape $n \times k$ and one with shape $k$, multiplies them together element-wise using broadcasting, then sums them along the second axis to get an array of shape $n$. Return that array.

This is one way to evaluate a linear model for multiple inputs.
Matrix multiplication will give a more concise way to do this.

In [23]:
# YOUR CHANGES HERE

def p6(x, y):
    ...

In [24]:
p6_test_x = np.array([[1, 2, 3], [4, 5, 6]])
p6_test_x

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
p6_test_x.shape

(2, 3)

In [28]:
p6_test_y = np.array([3, 5, 7])
p6_test_y

array([3, 5, 7])

In [29]:
p6_test_y.shape

(3,)

In [26]:
p6(p6_test_x, p6_test_y)

### Problem 7

Write a function `p7` that takes in a 1-dimensional array of values $z_i$, and returns an array composed of $\frac{e^{z_i}}{\sum e^{z_i}}$.
The output array shape should be the same as the input array shape.

This formula is the [softmax](https://en.wikipedia.org/wiki/Softmax_function) formula used to adjust raw machine learning outputs into more suitable probability estimates.

Hint: Use `numpy.exp`.


In [24]:
# YOUR CHANGES HERE

def p7(z):
    ...

In [ ]:
p7(np.array([1, 1, 1]))

In [ ]:
p7(np.array([-1, 0, 1]))

In [ ]:
p7(np.array([-1, -9, 9]))

This function is known as the softmax function, and is used to create a probability distribution biased towards the highest value.

### Problem 8

Write a function `p8` that takes in a 2-dimensional array and repeats the softmax calculation of problem 7 on a row-by-row basis.
That is, the output should be the same as if you split the input array into rows, applied the softmax formula to each row individually, and then recombined the rows again.
This calculation can be done much more concisely using Numpy without splitting the data into rows.
The output array shape should be the same as the input array shape.

Hint: Use the axis parameter with the sum.


In [25]:
# YOUR CHANGES HERE

def p8(z):
    ...

In [ ]:
# this test input has the p7 test inputs as rows, so you should be able to compare
# the output here with your p7 test output.

p8(np.array([[1, 1, 1], [-1, 0, 1], [-1, -9, 9]]))

### Problem 9

Write a function `p9` that takes in the name of a TSV file, reads an array of numbers from a file, and returns a 1-dimensional array with the average value from each column. You may assume that the file does not have a header.

In [26]:
# YOUR CHANGES HERE

def p9(filename):
    ...

In [ ]:
p9("f9.tsv")

### Problem 10

Write a function that takes in a NumPy array of any type, and returns an array with the same values with type float32. If the input array already has type float32, return the original array.


In [33]:
# YOUR CHANGES HERE

def p10(x):
    ...

In [30]:
p10_input_1 = np.array([0.0, 1,0])
p10_input_1

array([0., 1., 0.])

In [31]:
p10_input_1.dtype

dtype('float64')

In [34]:
p10(p10_input_1)

In [36]:
p10_input_2 = np.array([0.0, 1.0], dtype="float32")
p10_input_2

array([0., 1.], dtype=float32)

In [37]:
p10(p10_input_2)

### Problem 11

Write a function `p11` that takes in a 2-dimensional array and returns an array with the cumulative mean calculated along the second axis.
So the first row of the output shows the cumulative mean of the first row of the input.


 Hint: Use `numpy.cumsum` and `numpy.arange`.

In [28]:
# YOUR CHANGES HERE

def p11(x):
    ...

In [ ]:
p11(np.array([[0.2, 0.3, 0.4]]))

In [ ]:
p11(np.array([[0.2, 0.3, 0.4], [4.0, 3.0, 1.0]]))

### Problem 12

Write a function `p12` taking in a 2-dimensional array and returning `True` if each row of the array sums to one (test if it is between 0.999 and 1.001 to account for numerical inaccuracy) or `False` otherwise.


In [29]:
# YOUR CHANGES HERE

def p12(x):
    ...

In [ ]:
p12(np.array([[0.0, 1.0], [0.9999, 0.0000]]))

In [ ]:
p12(np.array([[0.3], [1.0]]))

### Problem 13

Write a function `p13` taking an $n \times k$ array and returns a tuple of arrays with the minimum, median, and maximum values of each row. To be clear, the function should return a tuple of three 1-dimensional arrays, each of length $n$.


In [30]:
# YOUR CHANGES HERE

def p13(x):
    ...

In [ ]:
p13(np.array([[1, 2, 3], [9, 9, 9], [1000, 100, 900]]))

### Problem 14

Write a function `p14` that takes in a two dimensional array and returns the highest row sum.

In [ ]:
# YOUR CHANGES HERE

def p14(a):
    ...

In [269]:
# should return 68

p14(np.array([[23, 1, 5], [13, 2, 53]]))

### Problem 15

Write a function `p15` that takes in a number as input, and returns a string like "The answer is 42.34 elephants." where the number in the returned string is the input number with two digits after the decimal point.

In [ ]:
# YOUR CHANGES HERE

def p15(v):
    ...

In [ ]:
# this should match the example

p15(42.341)

In [ ]:
p15(12.345)

In [ ]:
p15(1.1)

### Problem 16

Using NumPy, you can use functions such as `np.zeros`, `np.ones`, or `np.full` to create an array where all the contained values are initialized to the same number.

Write a function `p16` taking in a two dimensional array, and returning a tuple `(x, y, v)` that could be used to reconstruct the input array using `np.full`, or `None` if the array cannot be created with a call to `np.full`.
Note that the requested tuple is not exactly the arguments to `np.full`.

Hint: make sure to check that all the values in the input are the same.

In [ ]:
# YOUR CHANGES HERE

def p16(a):
    ...

In [ ]:
p16(np.array([[0]]))

In [ ]:
p16(np.array([[0, 1]]))

In [ ]:
p16(np.array([[3], [3]]))

In [ ]:
p16(np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4]]))

### Problem 17

[Kakuro](https://en.wikipedia.org/wiki/Kakuro) is a logic puzzle where the goal is to fill in numbers so that the rows and columns add up to specified numbers.
Write a function `p17` that checks if a given 2 dimensional array is a solution for the given row and column sum constraints and returns `True` if the are satisfied and `False` otherwise.

(This is a simplified version of the game limiting the filled cells to rectangle shapes, and does not include the duplicate check.)

In [ ]:
# YOUR CHANGES HERE

def p17(a, row_sums, column_sums):
    ...

In [ ]:
# this should return True

p17(np.array([[0, 1, 2], [3, 4, 5]]), [3, 12], [3, 5, 7])

In [ ]:
# this should return False

p17(np.array([[0, 2, 4], [3, 4, 5]]), [3, 12], [3, 5, 7])

### Problem 18

The function `p18` below is supposed to compute the dot product between two 1-dimensional arrays given as input.
The dot product is supposed to be calculated by multiplying corresponding values between the two arrays, and summing up those products.
The definition of `p18` below is incomplete.
Fix `p18` to correctly calculate the dot product.

In [ ]:
# YOUR CHANGES HERE

def p18(a, b):
    return a * b

In [ ]:
# should return 1*4 + 5*7 + 9*6 = 93

p18(np.array([1, 5, 9]), np.array([4, 7, 6]))

### Problem 19

Write a function `p19` that takes in a list of arrays as input, and returns the largest one (counting elements).
If there is more than one with the maximum number of elements, the tie may be broken arbitrarily.

In [ ]:
# YOUR CHANGES HERE

def p19(array_list):
    ...

In [ ]:
p19([np.zeros(1), np.ones((2, 2)), np.arange(20)])

### Problem 20

Write a function `p20` that takes in an $n \times 1$ array and an $1 \times m$ array as input, and returns `True` if any sum of a value in the first array with a value in the second array is 100 and `False` otherwise.

Hint: use broadcasting.

In [ ]:
# YOUR CHANGES HERE

def p20(a, b):
    ...

In [ ]:
# this should return True

p20(np.array([[20], [40], [50]]), np.array([50, 10, 30]))

In [ ]:
# this should return False

p20(np.array([[20], [40], [50]]), np.array([40, 10, 30]))